version: '3.5'
services:
 vfzsync:
  image: djettah/vfzsync:0.4.7
  restart: always
  volumes:
   - /etc/localtime:/etc/localtime:ro
#    - /etc/timezone:/etc/timezone:ro 
  env_file:
   - .env_vfzsync
