general:
  debug: false
  dryrun: false
  trace: false
  interval: 600
  loops: -1

vpoller:
  endpoint: tcp://address:port
  vc_host: address

zabbix:
  url: https://address
  username: username
  password: password
  hostgroup: FNT Command
  template: Template FNT Virtual Server
  proxy: zabbix-proxy-sqlite3


command:
  url: http://address:port
  username: username
  password: password

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s:%(name)s:%(levelname)s:%(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stderr
    file:
      class: logging.FileHandler
      level: ERROR
      formatter: simple
      filename: <defined_in_code.log>
  loggers:
    vfzsync:
      level: DEBUG
      handlers: [console, file]
      propagate: no
    pyzabbix:
      level: INFO
      handlers: [console, file]
      propagate: no
    requests.packages.urllib3:
      level: WARN
      handlers: [console, file]
      propagate: yes
  root:
    level: WARN
    handlers: [console, file]